path = 'C:\Espressif'
idf_path = 'C:\Espressif\v5.4.1\esp-idf'
esp_idf_json_path = 'C:\Espressif\tools'
tool_download_folder_name = 'C:\Espressif\dist'
tool_install_folder_name = 'C:\Espressif\tools'
target = ["esp32"]
idf_versions = ["v5.4.1"]
tools_json_file = "tools/tools.json"
config_file_save_path = "eim_config.toml"
non_interactive = true
wizard_all_questions = false
mirror = "https://github.com"
idf_mirror = "https://github.com"
pypi_mirror = "https://pypi.org/simple"
recurse_submodules = true
install_all_prerequisites = true
skip_prerequisites_check = false
cleanup = false
python_env_folder_name = "python"
activation_script_path_override = 'C:\Espressif\tools'
python_version_override = "python313"

[idf_features_per_version]
"v5.4.1" = ["core"]

[idf_tools_per_version]
"v5.4.1" = ["xtensa-esp-elf-gdb", "xtensa-esp-elf", "esp-clang", "esp32ulp-elf", "cmake", "openocd-esp32", "ninja", "idf-exe", "ccache", "esp-rom-elfs"]
